### ISSUE TITLE
[Feature] Telegram bot

### ISSUE THREAD

**Issue by henry3556108** [henry3556108/under_program_topic#2]
# Summary
need to create a telegram bot , that my model be a service

#Todo
- [ ] create Resnet telegram bot
- [ ] that the bot can receive one person's image and return image
- [ ] that the bot can receive mult person's images and return images

**Comment by henry3556108** [comment]
complete the bot , but doesn't have model
